### ISSUE TITLE
Occasional failures while rendering notebooks

### ISSUE THREAD

**Issue by angus-g** [g-adopt/g-adopt#143]
I think there's some kind of resource contention while rendering notebooks. The actual rendering works just fine, but ZMQ instances run into each other.

See: https://github.com/g-adopt/g-adopt/actions/runs/11806483870/attempts/1

**Comment by dsroberts** [comment]
@w3168 had this issue about a month ago, I got as far as its a race condition in either ipykernel or ZMQ between deciding a port is available and actually attempting to bind to it. I wasn't able to find any related issues on this on the ipykernel or ZMQ github repos.There is retry code in ZMQ but it doesn't appear to be used for this, ipykernel is selecting the port rather than letting ZMQ handle it.

**Comment by Patol75** [comment]
Would it make a difference if, instead of having `for ipynb; run jupytext on that ipynb`, we had `run jupytext on all ipynb`? In other words, `python3 -m jupytext --to ipynb --execute $(notebook_files)`.

**Comment by angus-g** [comment]
That wouldn't parallelise, to my knowledge.
